CREATE TABLE boat
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_boat PRIMARY KEY (id)
);


INSERT INTO boat (id, name, description) VALUES (1, 'Sailors Delight', 'A classic sailboat perfect for weekend getaways.');
INSERT INTO boat (id, name, description) VALUES (2, 'Ocean Explorer', 'A robust yacht equipped for deep-sea adventures.');
INSERT INTO boat (id, name, description) VALUES (3, 'Lake Cruiser', 'A comfortable motorboat ideal for lake and river cruises.');
